# Generated by Django 3.1.7 on 2021-03-14 12:24

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('driver', django.db.models.manager.Manager()),
            ],
        ),
    ]
