# Generated by Django 3.1.7 on 2021-03-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210314_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='genetated_otp',
            field=models.IntegerField(blank=True, null=True, verbose_name='OTP'),
        ),
    ]
