# Generated by Django 3.1.7 on 2021-03-15 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_genetated_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='genetated_otp',
            new_name='generated_otp',
        ),
    ]
