# Generated by Django 3.1.7 on 2021-03-18 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210316_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='generated_otp',
        ),
    ]
