# Generated by Django 3.1.7 on 2021-04-07 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp',
        ),
    ]
