# Generated by Django 3.1.7 on 2021-04-07 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup', models.CharField(max_length=255, verbose_name='Pickup Address')),
                ('dropoff', models.CharField(max_length=255, verbose_name='Drop-off Address')),
                ('status', models.CharField(choices=[('REQUESTED', 'requested'), ('STARTED', 'started'), ('IN_PROGRESS', 'in_progress'), ('COMPLETED', 'completed')], default='REQUESTED', max_length=20, verbose_name='Trips Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Trip Created On')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Trip Updated On')),
            ],
        ),
    ]
