# Generated by Django 3.1.7 on 2021-04-13 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_auto_20210414_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'requested'), ('STARTED', 'started'), ('PROGRESSING', 'progressing'), ('COMPLETED', 'completed')], default='REQUESTED', max_length=20, verbose_name='Trips Status'),
        ),
    ]
